version: '3'
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DB_DIALECT=mariadb
      - DB_HOST=mariadb:3306
      - DB_NAME=tododot
      - DB_USER=todo-adminrd
      - DB_PW=admin-pw

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=passwordlulu
      - MARIADB_DATABASE=tododot
      - MARIADB_USER=todo-admin
      - MARIADB_PASSWORD=admin-pw
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/todo

volumes:
  db_data:
